package com.splitit.splitit.backend.DAO;

public enum AuditoriaAccion {
	CAMBIOIMAGEN,
	CAMBIOMONEDA,
	CAMBIOTIPOGRUPO,
	NUEVACATEGORIAGRUPO,
	ELIMINACATEGORIAGRUPO,
	NUEVOPAGO,
	NUEVOGASTO,
	NUEVOAVATAR,
	NUEVAINVITACION,
	NUEVOGRUPO,
	ACEPTARINVITACION,
	//Esta es solo para el usuario
	CREACIONUSUARIO
}